"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const client_1 = require("@prisma/client");
const prisma = new client_1.PrismaClient();
const sampleProducts = [
    // ==================== MOISTURIZERS (14) ====================
    {
        name: 'Hydra Balance Oil-Free Gel Moisturizer',
        brand: 'Aura Skincare',
        category: 'Moisturizer',
        price: 799,
        size: '50ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['oil-control', 'hydration', 'pore-refining'],
        ingredients: ['Niacinamide', 'Hyaluronic Acid', 'Zinc PCA'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.6,
        description: 'An ultra-lightweight gel moisturizer designed specifically for oily skin. Controls excess sebum while keeping skin plump.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Barrier Repair Deep Moisture Cream',
        brand: 'DermaCure',
        category: 'Moisturizer',
        price: 1250,
        size: '50ml',
        skinTypes: ['dry', 'sensitive'],
        concerns: ['hydration', 'barrier-repair', 'soothing'],
        ingredients: ['Ceramides', 'Centella Asiatica', 'Squalane'],
        texture: 'cream',
        fragranceFree: true,
        rating: 4.8,
        description: 'Rich, restorative cream engineered to repair damaged skin barriers and relieve intense dry skin discomfort.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Aqua Surge Water Lotion',
        brand: 'GlowRx',
        category: 'Moisturizer',
        price: 599,
        size: '100ml',
        skinTypes: ['oily', 'normal', 'combination'],
        concerns: ['hydration', 'brightening'],
        ingredients: ['Hyaluronic Acid', 'Aloe Vera', 'Green Tea'],
        texture: 'water-based',
        fragranceFree: false,
        rating: 4.3,
        description: 'Refreshing water-gel formula that instantly hydrates with a non-sticky finish ideal for hot climates.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Calming Cica Soothing Cream',
        brand: 'PureBotanica',
        category: 'Moisturizer',
        price: 899,
        size: '50ml',
        skinTypes: ['sensitive', 'dry', 'combination'],
        concerns: ['soothing', 'redness', 'barrier-repair'],
        ingredients: ['Centella Asiatica', 'Madecassoside', 'Panthenol'],
        texture: 'cream',
        fragranceFree: true,
        rating: 4.7,
        description: 'Dermatologist-tested soothing cream that immediately calms irritated, redness-prone skin.',
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Matte Finishing Oil-Control Hydrator',
        brand: 'CleanGlow',
        category: 'Moisturizer',
        price: 499,
        size: '50ml',
        skinTypes: ['oily'],
        concerns: ['oil-control', 'acne', 'pore-refining'],
        ingredients: ['Salicylic Acid', 'Tea Tree Oil', 'Niacinamide'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.4,
        description: 'Mattifying daily hydrator formulated to prevent shine throughout the day while targeting breakouts.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Peptide Complex Firming Night Cream',
        brand: 'Aura Skincare',
        category: 'Moisturizer',
        price: 1850,
        size: '50ml',
        skinTypes: ['dry', 'normal'],
        concerns: ['anti-aging', 'hydration', 'firming'],
        ingredients: ['Peptides', 'Retinol', 'Shea Butter'],
        texture: 'cream',
        fragranceFree: false,
        rating: 4.9,
        description: 'Nourishing nocturnal moisturizer packed with active peptides to plump skin fine lines while you sleep.',
        imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Dewy Glow Vitamin C Cream Moisturizer',
        brand: 'Lumiere',
        category: 'Moisturizer',
        price: 950,
        size: '50ml',
        skinTypes: ['normal', 'combination'],
        concerns: ['brightening', 'hydration', 'dark-spots'],
        ingredients: ['Vitamin C', 'Alpha Arbutin', 'Hyaluronic Acid'],
        texture: 'lotion',
        fragranceFree: false,
        rating: 4.5,
        description: 'Brightening cream lotion infused with potent antioxidants to diminish hyperpigmentation and yield a radiant complexion.',
        imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Ultra Sensitive Oil-Free Moisture Lotion',
        brand: 'DermaCure',
        category: 'Moisturizer',
        price: 699,
        size: '100ml',
        skinTypes: ['sensitive', 'oily'],
        concerns: ['soothing', 'hydration'],
        ingredients: ['Allantoin', 'Glycerin', 'Squalane'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.6,
        description: 'Minimalist formula with zero fragrance, silicone, or pore-clogging oils. Safe for hypersensitive oily skin.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Squalane Hydrating Gel-Cream',
        brand: 'PureBotanica',
        category: 'Moisturizer',
        price: 849,
        size: '50ml',
        skinTypes: ['combination', 'oily', 'normal'],
        concerns: ['hydration', 'barrier-repair'],
        ingredients: ['Squalane', 'Hyaluronic Acid', 'Green Tea Extract'],
        texture: 'gel',
        fragranceFree: true,
        rating: 4.7,
        description: 'Biocompatible squalane gel-cream that locks moisture deeply into skin without greasiness.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Clarifying Tea Tree Mattifying Lotion',
        brand: 'CleanGlow',
        category: 'Moisturizer',
        price: 399,
        size: '50ml',
        skinTypes: ['oily'],
        concerns: ['acne', 'oil-control'],
        ingredients: ['Tea Tree Oil', 'Willow Bark Extract', 'Salicylic Acid'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.2,
        description: 'Affordable oil-control moisturizer formulated for acne-prone teenager and young adult skin.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Rich Honey Intense Nourishing Balm',
        brand: 'PureBotanica',
        category: 'Moisturizer',
        price: 1100,
        size: '50ml',
        skinTypes: ['dry', 'sensitive'],
        concerns: ['hydration', 'soothing', 'barrier-repair'],
        ingredients: ['Propolis Extract', 'Honey', 'Ceramides'],
        texture: 'cream',
        fragranceFree: false,
        rating: 4.8,
        description: 'Enriched honey balm providing heavy-duty hydration for flaky winter dry skin.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Ceramide Water Gel Moisturizer',
        brand: 'GlowRx',
        category: 'Moisturizer',
        price: 749,
        size: '60ml',
        skinTypes: ['oily', 'combination', 'sensitive'],
        concerns: ['barrier-repair', 'hydration'],
        ingredients: ['Ceramides', 'Hyaluronic Acid', 'Niacinamide'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.6,
        description: 'Water-gel delivery system bringing essential barrier repair ceramics to oily and break-out prone skin.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Niacinamide 5% Pore Vanishing Hydrator',
        brand: 'Lumiere',
        category: 'Moisturizer',
        price: 899,
        size: '50ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['pore-refining', 'oil-control', 'brightening'],
        ingredients: ['Niacinamide', 'Zinc PCA', 'Witch Hazel'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.5,
        description: 'High strength niacinamide moisturizer focused on shrinking enlarged pores and controlling T-zone shine.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Daily UV Defense Moisturizer SPF 30',
        brand: 'Aura Skincare',
        category: 'Moisturizer',
        price: 999,
        size: '75ml',
        skinTypes: ['normal', 'combination', 'dry'],
        concerns: ['hydration', 'sun-protection'],
        ingredients: ['Hyaluronic Acid', 'Tocopherol', 'Zinc Oxide'],
        texture: 'lotion',
        fragranceFree: true,
        rating: 4.4,
        description: 'Dual-action daily moisturizer infused with broad-spectrum SPF 30 protection.',
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=400',
    },
    // ==================== CLEANSERS (12) ====================
    {
        name: 'Salicylic Acid Pore Purifying Foaming Cleanser',
        brand: 'CleanGlow',
        category: 'Cleanser',
        price: 499,
        size: '150ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['acne', 'oil-control', 'pore-refining'],
        ingredients: ['Salicylic Acid', 'Tea Tree Oil', 'Zinc PCA'],
        texture: 'foam',
        fragranceFree: true,
        rating: 4.6,
        description: 'Deep pore foaming cleanser that dissolves excess sebum and unclogs blocked pores gently.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Gentle Hydrating Cream Cleanser',
        brand: 'DermaCure',
        category: 'Cleanser',
        price: 650,
        size: '200ml',
        skinTypes: ['dry', 'sensitive'],
        concerns: ['hydration', 'soothing', 'barrier-repair'],
        ingredients: ['Ceramides', 'Glycerin', 'Oat Extract'],
        texture: 'cream',
        fragranceFree: true,
        rating: 4.8,
        description: 'Non-foaming cream cleanser that gently washes away impurities while maintaining moisture barrier strength.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Cica Soothing Low pH Gel Cleanser',
        brand: 'PureBotanica',
        category: 'Cleanser',
        price: 599,
        size: '150ml',
        skinTypes: ['sensitive', 'combination', 'oily'],
        concerns: ['soothing', 'redness', 'barrier-repair'],
        ingredients: ['Centella Asiatica', 'Tea Tree Leaf Water', 'Panthenol'],
        texture: 'gel',
        fragranceFree: true,
        rating: 4.7,
        description: 'pH-balanced 5.5 gel cleanser designed to respect skin pH while thoroughly cleansing without tightness.',
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Brightening Vitamin C Facial Wash',
        brand: 'GlowRx',
        category: 'Cleanser',
        price: 449,
        size: '150ml',
        skinTypes: ['normal', 'combination'],
        concerns: ['brightening', 'dark-spots'],
        ingredients: ['Vitamin C', 'Lemon Peel Extract', 'Niacinamide'],
        texture: 'foam',
        fragranceFree: false,
        rating: 4.4,
        description: 'Energizing facial cleanser infused with citrus vitamin power to awaken dull skin tone.',
        imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Micellar Water Sensitive Cleansing Solution',
        brand: 'DermaCure',
        category: 'Cleanser',
        price: 349,
        size: '250ml',
        skinTypes: ['sensitive', 'all'],
        concerns: ['soothing', 'hydration'],
        ingredients: ['Micellar Water', 'Cucumber Extract', 'Glycerin'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.5,
        description: 'No-rinse gentle micellar cleanser that lifts makeup and dirt effortless without stinging.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Charcoal Detox Deep Cleansing Gel',
        brand: 'CleanGlow',
        category: 'Cleanser',
        price: 399,
        size: '100ml',
        skinTypes: ['oily'],
        concerns: ['oil-control', 'pore-refining'],
        ingredients: ['Activated Charcoal', 'Salicylic Acid', 'Aloe Vera'],
        texture: 'gel',
        fragranceFree: true,
        rating: 4.3,
        description: 'Activated charcoal gel cleanser that magnetically draws out stubborn blackheads and urban pollution.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Rice Milk Gentle Hydrating Cleanser',
        brand: 'Lumiere',
        category: 'Cleanser',
        price: 750,
        size: '150ml',
        skinTypes: ['dry', 'normal', 'sensitive'],
        concerns: ['brightening', 'hydration'],
        ingredients: ['Rice Bran Water', 'Squalane', 'Ceramides'],
        texture: 'lotion',
        fragranceFree: true,
        rating: 4.7,
        description: 'Traditional Asian rice extract cleanser leaving skin baby-soft and intensely hydrated.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'AHA Glycolic Resurfacing Cleanser',
        brand: 'Aura Skincare',
        category: 'Cleanser',
        price: 899,
        size: '120ml',
        skinTypes: ['combination', 'oily'],
        concerns: ['brightening', 'pore-refining', 'dark-spots'],
        ingredients: ['Glycolic Acid', 'Lactic Acid', 'Aloe Vera'],
        texture: 'gel',
        fragranceFree: false,
        rating: 4.5,
        description: 'Exfoliating AHA cleanser that dissolves dead surface skin cells to reveal smoother skin texture.',
        imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Oat Soothing Cleansing Balm',
        brand: 'PureBotanica',
        category: 'Cleanser',
        price: 999,
        size: '100g',
        skinTypes: ['dry', 'sensitive'],
        concerns: ['barrier-repair', 'soothing', 'hydration'],
        ingredients: ['Colloidal Oat', 'Oat Kernel Oil', 'Sunflower Seed Oil'],
        texture: 'cream',
        fragranceFree: true,
        rating: 4.8,
        description: 'Melt-away cleansing balm that removes waterproof makeup while cocooning dry sensitive skin.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Green Tea Refreshing Amino Cleanser',
        brand: 'GlowRx',
        category: 'Cleanser',
        price: 525,
        size: '150ml',
        skinTypes: ['combination', 'oily', 'normal'],
        concerns: ['oil-control', 'soothing'],
        ingredients: ['Green Tea Extract', 'Amino Acids', 'Glycerin'],
        texture: 'foam',
        fragranceFree: true,
        rating: 4.6,
        description: 'Antioxidant-rich green tea amino foam cleanser that balances oil without stripping natural lipids.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Acne Control Benzoyl Cleansing Wash',
        brand: 'CleanGlow',
        category: 'Cleanser',
        price: 475,
        size: '125ml',
        skinTypes: ['oily'],
        concerns: ['acne', 'oil-control'],
        ingredients: ['Benzoyl Peroxide', 'Niacinamide', 'Aloe Vera'],
        texture: 'foam',
        fragranceFree: true,
        rating: 4.3,
        description: 'Targeted medicinal wash formulated to reduce acne bacteria and stubborn inflamed breakouts.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Triple Hyaluronic Acid Milky Wash',
        brand: 'Aura Skincare',
        category: 'Cleanser',
        price: 799,
        size: '150ml',
        skinTypes: ['dry', 'normal'],
        concerns: ['hydration', 'barrier-repair'],
        ingredients: ['Hyaluronic Acid', 'Panthenol', 'Squalane'],
        texture: 'lotion',
        fragranceFree: true,
        rating: 4.7,
        description: 'Milky lotion wash containing 3 molecular weights of Hyaluronic Acid for layered moisture.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    // ==================== SERUMS (13) ====================
    {
        name: 'Niacinamide 10% + Zinc 1% Oil Control Serum',
        brand: 'Aura Skincare',
        category: 'Serum',
        price: 699,
        size: '30ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['oil-control', 'pore-refining', 'acne', 'dark-spots'],
        ingredients: ['Niacinamide', 'Zinc PCA', 'Hyaluronic Acid'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.8,
        description: 'High-concentration B3 serum designed to minimize oiliness, refine large pores, and fade post-acne scars.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Pure Hyaluronic 2% Deep Hydration Serum',
        brand: 'GlowRx',
        category: 'Serum',
        price: 599,
        size: '30ml',
        skinTypes: ['dry', 'sensitive', 'normal', 'oily', 'combination'],
        concerns: ['hydration', 'soothing'],
        ingredients: ['Hyaluronic Acid', 'Vitamin B5', 'Glycerin'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.7,
        description: 'Universal hydration booster that draws 1,000x its weight in water to plump fine dry dehydration lines.',
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Vitamin C 15% Glow & Anti-Spot Serum',
        brand: 'Lumiere',
        category: 'Serum',
        price: 1199,
        size: '30ml',
        skinTypes: ['normal', 'combination', 'dry'],
        concerns: ['brightening', 'dark-spots', 'anti-aging'],
        ingredients: ['L-Ascorbic Acid', 'Ferulic Acid', 'Vitamin E'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.6,
        description: 'Stabilized Vitamin C formula fortified with Ferulic acid to brighten sun spots and hyperpigmentation.',
        imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Salicylic Acid 2% BHA Clarifying Serum',
        brand: 'CleanGlow',
        category: 'Serum',
        price: 549,
        size: '30ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['acne', 'pore-refining', 'oil-control'],
        ingredients: ['Salicylic Acid', 'Witch Hazel', 'Green Tea'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.5,
        description: 'Oil-soluble BHA serum that penetrates deep into pore linings to dissolve clogged sebum and blackheads.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Advanced 0.3% Retinol Night Serum',
        brand: 'DermaCure',
        category: 'Serum',
        price: 1450,
        size: '30ml',
        skinTypes: ['normal', 'dry', 'combination'],
        concerns: ['anti-aging', 'pore-refining', 'dark-spots'],
        ingredients: ['Retinol', 'Squalane', 'Peptides'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.7,
        description: 'Encapsulated gentle retinol serum targeting wrinkles and rough skin texture with reduced irritation risk.',
        imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Cica Repair Barrier Serum',
        brand: 'PureBotanica',
        category: 'Serum',
        price: 899,
        size: '40ml',
        skinTypes: ['sensitive', 'dry'],
        concerns: ['barrier-repair', 'soothing', 'redness'],
        ingredients: ['Centella Asiatica', 'Panthenol', 'Madecassoside'],
        texture: 'gel',
        fragranceFree: true,
        rating: 4.8,
        description: 'Emergency rescue serum designed to calm flare-ups, over-exfoliation redness, and skin sensitivity.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Alpha Arbutin 2% Dark Spot Corrector',
        brand: 'Lumiere',
        category: 'Serum',
        price: 799,
        size: '30ml',
        skinTypes: ['all'],
        concerns: ['dark-spots', 'brightening'],
        ingredients: ['Alpha Arbutin', 'Hyaluronic Acid', 'Kojic Acid'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.5,
        description: 'Targeted skin tone equalizer that visibly lightens stubborn dark marks caused by sun damage or pimples.',
        imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Multi-Peptide Youth Matrix Serum',
        brand: 'Aura Skincare',
        category: 'Serum',
        price: 1699,
        size: '30ml',
        skinTypes: ['dry', 'normal', 'combination'],
        concerns: ['anti-aging', 'firming', 'hydration'],
        ingredients: ['Peptides', 'Matrixyl 3000', 'Hyaluronic Acid'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.9,
        description: 'Comprehensive anti-aging peptide cocktail stimulating collagen synthesis for firmer, younger-looking skin.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: '100% Plant-Derived Squalane Moisture Serum',
        brand: 'PureBotanica',
        category: 'Serum',
        price: 749,
        size: '30ml',
        skinTypes: ['dry', 'sensitive', 'combination'],
        concerns: ['hydration', 'barrier-repair'],
        ingredients: ['Squalane'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.7,
        description: 'Single-ingredient pure plant squalane oil serum that locks moisture without clogging pores.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'AHA 10% + BHA 2% Exfoliating Peeling Solution',
        brand: 'CleanGlow',
        category: 'Serum',
        price: 699,
        size: '30ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['brightening', 'pore-refining', 'dark-spots'],
        ingredients: ['Glycolic Acid', 'Salicylic Acid', 'Tasmanian Pepperberry'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.4,
        description: '10-minute rinse-off chemical exfoliant treatment for deep pore cleansing and glowing skin renewal.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Polyglutamic Acid Intense Plumping Serum',
        brand: 'GlowRx',
        category: 'Serum',
        price: 849,
        size: '30ml',
        skinTypes: ['dry', 'normal'],
        concerns: ['hydration', 'firming'],
        ingredients: ['Polyglutamic Acid', 'Hyaluronic Acid'],
        texture: 'gel',
        fragranceFree: true,
        rating: 4.6,
        description: 'Holds 4x more moisture than hyaluronic acid alone. Creates an incredible dewy bouncy skin finish.',
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Propolis 83% Glow Boosting Ampoule Serum',
        brand: 'PureBotanica',
        category: 'Serum',
        price: 1299,
        size: '30ml',
        skinTypes: ['dry', 'combination', 'sensitive'],
        concerns: ['brightening', 'soothing', 'hydration'],
        ingredients: ['Propolis Extract', 'Honey', 'Niacinamide'],
        texture: 'gel',
        fragranceFree: false,
        rating: 4.8,
        description: 'Honey propolis serum yielding instant glass-skin radiance while soothing irritated flare-ups.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Azelaic Acid 10% Redness Relief Serum',
        brand: 'DermaCure',
        category: 'Serum',
        price: 899,
        size: '30ml',
        skinTypes: ['sensitive', 'oily', 'combination'],
        concerns: ['redness', 'acne', 'dark-spots'],
        ingredients: ['Azelaic Acid', 'Allantoin', 'Niacinamide'],
        texture: 'cream',
        fragranceFree: true,
        rating: 4.6,
        description: 'Multi-tasking treatment serum reducing rosacea redness, acne blemishes, and hyperpigmentation marks.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    // ==================== SUNSCREENS (12) ====================
    {
        name: 'Invisible Fluid Sunscreen SPF 50+ PA++++',
        brand: 'Aura Skincare',
        category: 'Sunscreen',
        price: 799,
        size: '50ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['sun-protection', 'oil-control'],
        ingredients: ['Tinosorb M', 'Niacinamide', 'Cica'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.8,
        description: 'Ultra-fluid daily sunscreen offering zero white cast, non-sticky finish, and strong oil control.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Hydrating Aqua Sun Gel SPF 50',
        brand: 'GlowRx',
        category: 'Sunscreen',
        price: 649,
        size: '50ml',
        skinTypes: ['dry', 'normal', 'combination'],
        concerns: ['sun-protection', 'hydration'],
        ingredients: ['Hyaluronic Acid', 'Aloe Vera', 'Uvinul A Plus'],
        texture: 'gel',
        fragranceFree: true,
        rating: 4.7,
        description: 'Cooling sun gel that feels like a moisturizer and melts into skin effortlessly with high UV protection.',
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Mineral Zinc Shield Sunscreen SPF 50',
        brand: 'DermaCure',
        category: 'Sunscreen',
        price: 899,
        size: '50ml',
        skinTypes: ['sensitive', 'dry'],
        concerns: ['sun-protection', 'soothing'],
        ingredients: ['Zinc Oxide', 'Titanium Dioxide', 'Centella Asiatica'],
        texture: 'cream',
        fragranceFree: true,
        rating: 4.6,
        description: '100% physical mineral sunscreen formulated specifically for reactive sensitive and post-procedure skin.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Matte Touch Dry-Oil Sunscreen SPF 50',
        brand: 'CleanGlow',
        category: 'Sunscreen',
        price: 499,
        size: '50ml',
        skinTypes: ['oily'],
        concerns: ['sun-protection', 'oil-control'],
        ingredients: ['Silica', 'Zinc Oxide', 'Green Tea'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.4,
        description: 'Affordable matte finish sun lotion designed for extreme grease control under summer humid weather.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Centella Air-Fit Sunscreen SPF 50+',
        brand: 'PureBotanica',
        category: 'Sunscreen',
        price: 950,
        size: '50ml',
        skinTypes: ['sensitive', 'combination', 'oily'],
        concerns: ['sun-protection', 'soothing', 'redness'],
        ingredients: ['Centella Asiatica', 'Niacinamide', 'Tocopherol'],
        texture: 'lotion',
        fragranceFree: true,
        rating: 4.9,
        description: 'Weightless Korean Cica sun lotion that calms redness while shielding skin from broad spectrum rays.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Vitamin C Radiance Glow Sunscreen SPF 50',
        brand: 'Lumiere',
        category: 'Sunscreen',
        price: 849,
        size: '50ml',
        skinTypes: ['normal', 'combination'],
        concerns: ['sun-protection', 'brightening', 'dark-spots'],
        ingredients: ['Vitamin C', 'Niacinamide', 'Avobenzone'],
        texture: 'lotion',
        fragranceFree: false,
        rating: 4.5,
        description: 'Sunscreen infused with brightening Vitamin C to prevent photo-aging and dark spot recurrence.',
        imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Silicone Matte Velvet Sun Fluid SPF 50',
        brand: 'Aura Skincare',
        category: 'Sunscreen',
        price: 999,
        size: '50ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['sun-protection', 'pore-refining', 'oil-control'],
        ingredients: ['Dimethicone', 'Tinosorb S', 'Vitamin E'],
        texture: 'gel',
        fragranceFree: true,
        rating: 4.6,
        description: 'Priming sunscreen gel that doubles as a makeup base by smoothing out enlarged pores and shine.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Rich Moisture Nourishing Sun Cream SPF 50',
        brand: 'DermaCure',
        category: 'Sunscreen',
        price: 799,
        size: '75ml',
        skinTypes: ['dry'],
        concerns: ['sun-protection', 'hydration', 'barrier-repair'],
        ingredients: ['Ceramides', 'Shea Butter', 'Titanium Dioxide'],
        texture: 'cream',
        fragranceFree: true,
        rating: 4.5,
        description: 'Deeply moisturizing sun cream providing heavy-duty UV defense and long-lasting dry skin nourishment.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Clear Water Sun Mist SPF 50',
        brand: 'GlowRx',
        category: 'Sunscreen',
        price: 699,
        size: '100ml',
        skinTypes: ['all'],
        concerns: ['sun-protection'],
        ingredients: ['Aloe Vera', 'Green Tea Extract', 'Chemical UV Filters'],
        texture: 'water-based',
        fragranceFree: false,
        rating: 4.3,
        description: 'Convenient spray sunscreen mist for quick re-application over makeup throughout outdoors.',
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Acne Defense Tinted Mineral Sunscreen SPF 40',
        brand: 'CleanGlow',
        category: 'Sunscreen',
        price: 649,
        size: '50ml',
        skinTypes: ['oily', 'sensitive'],
        concerns: ['sun-protection', 'acne', 'redness'],
        ingredients: ['Zinc Oxide', 'Niacinamide', 'Iron Oxides'],
        texture: 'lotion',
        fragranceFree: true,
        rating: 4.5,
        description: 'Universal tinted mineral sunscreen neutralising redness and acne scars while shielding skin.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Birch Juice Hydrating Sun Cream SPF 50+',
        brand: 'PureBotanica',
        category: 'Sunscreen',
        price: 1199,
        size: '50ml',
        skinTypes: ['dry', 'normal', 'sensitive'],
        concerns: ['sun-protection', 'hydration'],
        ingredients: ['Birch Juice', 'Hyaluronic Acid', 'Niacinamide'],
        texture: 'cream',
        fragranceFree: true,
        rating: 4.9,
        description: 'Award-winning hydrating sun cream infused with sap from Korean Birch trees for profound hydration.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Daily Hydro Shield Sun Fluid SPF 30',
        brand: 'Aura Skincare',
        category: 'Sunscreen',
        price: 549,
        size: '50ml',
        skinTypes: ['normal', 'combination'],
        concerns: ['sun-protection', 'hydration'],
        ingredients: ['Glycerin', 'Panthenol', 'Chemical Filters'],
        texture: 'lightweight',
        fragranceFree: true,
        rating: 4.4,
        description: 'Lightweight everyday urban sun fluid suitable for indoor office workers needing light sun protection.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    // ==================== TONERS (10) ====================
    {
        name: 'BHA 2% Liquid Pore Exfoliating Toner',
        brand: 'CleanGlow',
        category: 'Toner',
        price: 699,
        size: '118ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['pore-refining', 'oil-control', 'acne'],
        ingredients: ['Salicylic Acid', 'Green Tea Extract', 'Methylpropanediol'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.8,
        description: 'Cult-favorite BHA toner that sheds built-up skin layers and unclogs pores for clearer skin.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Hyaluronic Acid 5 Moist Toner',
        brand: 'GlowRx',
        category: 'Toner',
        price: 650,
        size: '200ml',
        skinTypes: ['dry', 'sensitive', 'normal'],
        concerns: ['hydration', 'barrier-repair'],
        ingredients: ['Hyaluronic Acid', 'Beta-Glucan', 'Panthenol'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.7,
        description: 'Viscous hydration toner containing 5 types of hyaluronic acid to quench dehydrated skin cells.',
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Centella Unscented Calming Toner',
        brand: 'PureBotanica',
        category: 'Toner',
        price: 799,
        size: '200ml',
        skinTypes: ['sensitive', 'dry', 'oily'],
        concerns: ['soothing', 'redness', 'barrier-repair'],
        ingredients: ['Centella Asiatica', 'Witch Hazel Extract', 'Sodium Hyaluronate'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.9,
        description: 'Alcohol-free and essential-oil-free soothing toner formulated for sensitive skin prone to redness.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Glycolic Acid 7% Toning Solution',
        brand: 'Aura Skincare',
        category: 'Toner',
        price: 799,
        size: '240ml',
        skinTypes: ['normal', 'combination', 'oily'],
        concerns: ['brightening', 'pore-refining', 'dark-spots'],
        ingredients: ['Glycolic Acid', 'Tasmanian Pepperberry', 'Ginseng Root'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.6,
        description: 'Targeted acid toner offering mild exfoliation for improved skin clarity and visible radiance.',
        imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Rice Glow Milky Hydrating Toner',
        brand: 'Lumiere',
        category: 'Toner',
        price: 999,
        size: '150ml',
        skinTypes: ['dry', 'normal', 'combination'],
        concerns: ['brightening', 'hydration'],
        ingredients: ['Rice Extract', 'Niacinamide', 'Adenosine'],
        texture: 'lotion',
        fragranceFree: true,
        rating: 4.8,
        description: 'Dual-phase milky toner infused with 77% rice extract for luminous, hydrated glowing skin.',
        imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Tea Tree Mattifying Clarifying Toner',
        brand: 'CleanGlow',
        category: 'Toner',
        price: 349,
        size: '200ml',
        skinTypes: ['oily'],
        concerns: ['acne', 'oil-control'],
        ingredients: ['Tea Tree Oil', 'Willow Bark', 'Zinc PCA'],
        texture: 'water-based',
        fragranceFree: false,
        rating: 4.2,
        description: 'Refreshing oil-absorbing toner with mattifying tapioca powders to absorb excessive shine.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Snail Mucin 96% Power Repair Essence Toner',
        brand: 'GlowRx',
        category: 'Toner',
        price: 1199,
        size: '100ml',
        skinTypes: ['dry', 'sensitive', 'combination'],
        concerns: ['barrier-repair', 'hydration', 'soothing'],
        ingredients: ['Snail Secretion Filtrate', 'Hyaluronic Acid', 'Allantoin'],
        texture: 'gel',
        fragranceFree: true,
        rating: 4.9,
        description: 'Rich essence toner that repairs skin damage, improves elasticity, and soothes dry patches.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Heartleaf 77% Soothing Relief Toner',
        brand: 'PureBotanica',
        category: 'Toner',
        price: 1099,
        size: '250ml',
        skinTypes: ['sensitive', 'oily', 'acne-prone'],
        concerns: ['soothing', 'acne', 'redness'],
        ingredients: ['Heartleaf Extract', 'Centella Asiatica', 'Panthenol'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.8,
        description: 'Highly effective calming toner formulated with 77% Heartleaf extract to soothe stubborn acne flare-ups.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Pore Tightening Witch Hazel Toner',
        brand: 'DermaCure',
        category: 'Toner',
        price: 499,
        size: '200ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['pore-refining', 'oil-control'],
        ingredients: ['Witch Hazel', 'Aloe Vera', 'Niacinamide'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.3,
        description: 'Alcohol-free witch hazel toner that refines visible pores and balances sebum production.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'AHA/BHA Clarifying Treatment Toner Mist',
        brand: 'Aura Skincare',
        category: 'Toner',
        price: 649,
        size: '150ml',
        skinTypes: ['combination', 'oily'],
        concerns: ['pore-refining', 'acne', 'brightening'],
        ingredients: ['Willow Bark Water', 'Apple Fruit Water', 'Glycolic Acid'],
        texture: 'water-based',
        fragranceFree: true,
        rating: 4.5,
        description: 'Daily gentle exfoliating mist toner that prevents whiteheads and blackheads before they form.',
        imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=400',
    },
    // ==================== FACE MASKS (9) ====================
    {
        name: 'Jeju Volcanic Pore Purifying Clay Mask',
        brand: 'CleanGlow',
        category: 'Face Mask',
        price: 599,
        size: '100g',
        skinTypes: ['oily', 'combination'],
        concerns: ['oil-control', 'pore-refining', 'acne'],
        ingredients: ['Volcanic Ash', 'Kaolin Clay', 'Lactic Acid'],
        texture: 'clay',
        fragranceFree: false,
        rating: 4.7,
        description: 'Deep-cleansing clay mask formulated with Jeju volcanic clusters to absorb excess oil and tighten pores.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Hyaluronic Acid Overnight Hydrating Sleeping Mask',
        brand: 'GlowRx',
        category: 'Face Mask',
        price: 899,
        size: '70ml',
        skinTypes: ['dry', 'normal', 'sensitive'],
        concerns: ['hydration', 'barrier-repair'],
        ingredients: ['Hyaluronic Acid', 'Squalane', 'Ceramides'],
        texture: 'cream',
        fragranceFree: true,
        rating: 4.8,
        description: 'Leave-on overnight gel-cream mask that re-hydrates tired skin while you sleep for morning glow.',
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Cica Soothing Sheet Mask (Pack of 5)',
        brand: 'PureBotanica',
        category: 'Face Mask',
        price: 499,
        size: '5 sheets',
        skinTypes: ['sensitive', 'dry', 'oily'],
        concerns: ['soothing', 'redness', 'hydration'],
        ingredients: ['Centella Asiatica', 'Tea Tree Oil', 'Allantoin'],
        texture: 'sheet',
        fragranceFree: true,
        rating: 4.8,
        description: 'Biodegradable cellulose sheet masks drenched in calming Cica serum for instant redness relief.',
        imageUrl: 'https://images.unsplash.com/photo-1608248597379-880c85c25785?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Vitamin C Brightening Sheet Mask (Pack of 5)',
        brand: 'Lumiere',
        category: 'Face Mask',
        price: 549,
        size: '5 sheets',
        skinTypes: ['normal', 'combination'],
        concerns: ['brightening', 'dark-spots'],
        ingredients: ['Vitamin C', 'Niacinamide', 'Glutathione'],
        texture: 'sheet',
        fragranceFree: false,
        rating: 4.6,
        description: 'Instant event-ready brightening sheet masks packed with Vitamin C and Glutathione radiant antioxidants.',
        imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Salicylic Acid 2% Clarifying Wash-Off Mask',
        brand: 'Aura Skincare',
        category: 'Face Mask',
        price: 749,
        size: '50ml',
        skinTypes: ['oily', 'combination'],
        concerns: ['acne', 'oil-control', 'pore-refining'],
        ingredients: ['Salicylic Acid', 'Charcoal', 'Kaolin'],
        texture: 'clay',
        fragranceFree: true,
        rating: 4.5,
        description: 'Smooth charcoal-infused clay mask targeting stubborn blackheads and active blemishes in 10 minutes.',
        imageUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Propolis Honey Hydrating Nourishing Mask',
        brand: 'PureBotanica',
        category: 'Face Mask',
        price: 999,
        size: '100g',
        skinTypes: ['dry', 'sensitive'],
        concerns: ['hydration', 'soothing', 'barrier-repair'],
        ingredients: ['Propolis Extract', 'Real Honey', 'Royal Jelly'],
        texture: 'cream',
        fragranceFree: false,
        rating: 4.9,
        description: 'Decadent honey wash-off mask providing deep replenishment for parched dry winter skin.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Tea Tree Blemish Control Hydrogel Mask',
        brand: 'CleanGlow',
        category: 'Face Mask',
        price: 299,
        size: '1 sheet',
        skinTypes: ['oily', 'acne-prone'],
        concerns: ['acne', 'soothing'],
        ingredients: ['Tea Tree Leaf Oil', 'Centella Asiatica', 'Zinc PCA'],
        texture: 'sheet',
        fragranceFree: true,
        rating: 4.4,
        description: 'Cooling hydrogel mask that locks antibacterial tea tree active directly into acne spots.',
        imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Resurfacing Glycolic Gel Peel Mask',
        brand: 'Aura Skincare',
        category: 'Face Mask',
        price: 1199,
        size: '50ml',
        skinTypes: ['normal', 'combination', 'oily'],
        concerns: ['brightening', 'pore-refining', 'dark-spots'],
        ingredients: ['Glycolic Acid', 'Lactic Acid', 'Fruit Enzymes'],
        texture: 'gel',
        fragranceFree: true,
        rating: 4.6,
        description: 'At-home chemical peel gel mask that transforms dull skin texture into glowing smooth glass skin.',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=400',
    },
    {
        name: 'Calming Oat Moisture Rescue Mask',
        brand: 'DermaCure',
        category: 'Face Mask',
        price: 799,
        size: '100g',
        skinTypes: ['sensitive', 'dry'],
        concerns: ['soothing', 'barrier-repair', 'redness'],
        ingredients: ['Colloidal Oatmeal', 'Aloe Vera', 'Ceramides'],
        texture: 'cream',
        fragranceFree: true,
        rating: 4.7,
        description: 'Velvety oat cream mask formulated to extinguish itchiness, irritation, and sunburn discomfort.',
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    },
];
async function main() {
    console.log('[Seed Script] Starting product database seeding...');
    // Clear existing products to ensure clean seed execution repeatedly
    await prisma.product.deleteMany({});
    console.log('[Seed Script] Cleared existing product records.');
    let createdCount = 0;
    for (const productData of sampleProducts) {
        await prisma.product.create({
            data: productData,
        });
        createdCount++;
    }
    console.log(`[Seed Script] Successfully seeded ${createdCount} products into PostgreSQL!`);
}
main()
    .catch((e) => {
    console.error('[Seed Script] Error seeding database:', e);
    process.exit(1);
})
    .finally(async () => {
    await prisma.$disconnect();
});
